version: '3'
services:
# DATABASE
  db:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: smhoezma
    ports:
    - 3306:3306
    volumes:
    - ./mysql/sql_scripts/:/docker-entrypoint-initdb.d
    - ./mysql/dev_data:/var/lib/mysql/
    networks:
    - default


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 80:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

