version: '3'
services:
  api_bridge:
    build: ./API_Bridge
    ports:
      - "5001:5000"
    links:
      - db
  api_nodemcu:
    build: ./API_NodeMCU
    ports:
      - "5002:5000"
    links:
      - db
  api_smhoezma:
    build: ./API_SmHoEzMa
    ports:
      - "5003:5000"
    links:
      - db

# DATABASE'
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      #- /mysql/startup.sql:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 80:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:

# docker-compose down -v --rmi all
# docker-compose up -d --force-recreate --build
# docker system prune